# Generated by Django 3.1.3 on 2020-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijibanpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokomodel',
            name='username',
            field=models.CharField(default='匿名', max_length=12),
        ),
    ]
