# Generated by Django 3.1.3 on 2020-12-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keijibanpost', '0002_tokomodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokomodel',
            name='username',
        ),
    ]
